version: "3.8"
volumes:
  php-fpm-socket:
  pma-session-store:
  db-store:
  db-store-test:
  vendor-store:
  node_modules-store:
services:
  app:
    build: ./infra/docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./api:/work/api
      - ./api/vendor:/work/api/vendor
    depends_on:
      - db
      - dbtest

  web:
    build: ./infra/docker/nginx
    ports:
      - 8000:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./api:/work/api
      - node_modules-store:/work/api/node_modules

  db:
    build: ./infra/docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./infra/docker/mysql/db:/var/lib/mysql

  dbtest:
    build: ./infra/docker/mysql
    ports:
      - 3307:3306
    volumes:
      - ./infra/docker/mysql/db-test:/var/lib/mysql

  cs:
    image: herloct/php-cs-fixer
    volumes:
      - ./api:/project

  pma:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
    ports:
      - 8080:80
    volumes:
      - pma-session-store:/sessions
    depends_on:
      - db
