name: lint

on:
  pull_request:
    paths:
      - "main/**"
      - "!**.md"
      - "!.editorconfig"
      - "!.gitignore"
      - "!.gitattributes"

jobs:
  main-run-linters:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./main

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Enable linters
          eslint: true
          prettier: true
          eslint_dir: ./main
          prettier_dir: ./main
          auto_fix: true
