name: lint

on:
  pull_request:

jobs:
  admin-run-linters:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./admin

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Enable linters
          eslint: true
          prettier: true
          eslint_dir: ./admin
          prettier_dir: ./admin
          auto_fix: true

  main-run-linters:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./main

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Enable linters
          eslint: true
          prettier: true
          eslint_dir: ./main
          prettier_dir: ./main
          auto_fix: true
